name:                compound-interest-api
version:             1.0.0
github:              "yourusername/lp-recuperacao-js-hs-compound"
license:             MIT
author:              "Your Name"
maintainer:          "your.email@example.com"
copyright:           "2025 Your Name"

extra-source-files:
- README.md

description:         Backend API em Haskell para cálculo de juros compostos

dependencies:
- base >= 4.7 && < 5
- scotty >= 0.12
- aeson >= 2.0
- text
- wai-cors >= 0.2
- wai
- http-types

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  compound-interest-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
